### ISSUE TITLE
给容器加上默认名

### ISSUE THREAD

**Issue by mashirot** [getmoneynote/docker-compose-moneynote-hub#14]
增加container_name属性
```yaml
version: '2.1'

services:
  moneywhere-api-user:
    container_name: moneywhere-api-user
    image: markliu2018/moneywhere-api-user:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: api-no-mysql.env
    ports:
      - "43742:9092"

  moneywhere-fe-user:
    container_name: moneywhere-fe-user
    links:
      - moneywhere-api-user
    image: markliu2018/moneywhere-fe-user:latest
    environment:
      USER_API_HOST: http://moneywhere-api-user:9092
    ports:
      - "43743:80"

  moneywhere-fe-user-mobile:
    container_name: moneywhere-fe-user-mobile
    links:
      - moneywhere-api-user
    image: markliu2018/moneywhere-fe-user-mobile:latest
    environment:
      USER_API_HOST: http://moneywhere-api-user:9092
    ports:
      - "43744:80"

```
